Add logical-version field version to the manifest schema
wildfly-extras/wildfly-channel pull request #281
Opened 2024-07-24 16:19 UTC by spyrkob

Add an optional `logical-version` field to the manifest schema. The new field can be used to provide a short human-readable information about the version of the manifest

2024-07-24 16:21 UTC, spyrkob commented
@jmesnil could you review this please?

2024-08-12 11:50 UTC, jmesnil requested changes

2024-08-12 11:50 UTC, jmesnil commented on core/src/main/java/org/wildfly/channel/ChannelManifest.java
> +                           String localVersion,
s/localVersion/logicalVersion ?

2024-10-15 06:52 UTC, jmesnil approved these changes

2024-10-15 06:52 UTC, merged