[#74] Using Bulk artifact resolve operations
wildfly-extras/wildfly-channel pull request #75
Opened 2022-06-24 10:17 UTC by spyrkob

Fixes #74

2022-06-24 12:08 UTC, jmesnil requested changes
@spyrkob I like this idea.

2022-06-24 12:08 UTC, jmesnil commented on core/src/main/java/org/wildfly/channel/DefaultArtifactCoordinate.java
> +public class DefaultArtifactCoordinate implements ArtifactCoordinate {
We could make the ArtifactCoordinate a class and merge the `ArtifactCoordinate` and `DefaultArtifactCoordinate` together. wdyt?

2022-06-24 12:08 UTC, jmesnil commented on core/src/main/java/org/wildfly/channel/DefaultArtifactCoordinate.java
> +
it's missing a `requireNonNumm(version)`

2022-06-24 12:08 UTC, jmesnil commented on maven-resolver/src/main/java/org/wildfly/channel/maven/VersionResolverFactory.java
> +                requireNonNull(coord.getGroupId());
you should not need it as the `ArtifactCoordinate` ctor wil already have these `requireNonNull`

2022-06-24 12:08 UTC, jmesnil commented on core/src/main/java/org/wildfly/channel/spi/MavenVersionsResolver.java
> +    * @throws UnresolvedMavenArtifactException if th artifact can not be resolved.
should be?

`@throws UnresolvedMavenArtifactException if any artifact can not be resolved.`

2022-06-24 13:02 UTC, spyrkob commented on core/src/main/java/org/wildfly/channel/ChannelRecorder.java
> +        List<Stream> sortedStreams = new ArrayList<>(streams.values());
I missed that change, sorry. I'll remove it.

2022-06-24 14:32 UTC, spyrkob commented
Pushed the changes.

Thinking a bit more about the ArtifactCoordinate, I'm wondering if it'd be worth to change it to:
```
ArtifactCoordinate (doesn't enforce anything)
 | - StreamArtifactCoordinate (requires only groupId and artifactId)
 | - ResolvabelArtifactCoordinate(requires groupId, artifactId and version)
 |   |- MavenArtifact(requires GAV and file)
 | - ChannelCoordinate (requires either GA, GAV or file)
```

This way eg. MavenVersionResolver#resolveArtifact can rely on ResolvabelArtifactCoordinate and ChannelSession#resolveMavenArtifacts can use StreamArtifactCoordinate to pass incomplete coordinate.

2022-06-27 08:15 UTC, jmesnil commented
I think we can simplify the coordinate tree. 
We could separate the `ChannelCoordinate` from the rest as it is used in a different code path.

```
ChannelCoordinate (requires either GA, GAV or file)
```

Then for the streams coordinate, we need 2 levels:

```
class ArtifactCoordinate (requires non-null groupId, artifactId, version)
   -> all API method requires to pass the base version of the coordinate when using the API
  |- class MavenArtfifact (require non-null file)
```

2022-06-27 09:42 UTC, spyrkob commented
> all API method requires to pass the base version of the coordinate when using the API
I forgot there's the base version as well. 

Separated ChannelCoordinate and made version required in ArtifactCoordinate

2022-06-29 08:48 UTC, jmesnil approved these changes

2022-06-29 08:49 UTC, merged

2022-06-29 08:49 UTC, jmesnil commented
@spyrkob thanks!